from __future__ import annotations

import html
from collections.abc import Callable, Sequence

from maintainer_radar.models import RepositorySnapshot
from maintainer_radar.scoring import Finding, ScoringConfig

DASHBOARD_MARKER = "<!-- maintainer-radar-dashboard -->"


def render_report(
    snapshot: RepositorySnapshot,
    findings: Sequence[Finding],
    config: ScoringConfig,
    *,
    max_items: int = 10,
    ai_summary: str | None = None,
) -> str:
    max_items = max(0, max_items)
    issues = sum(item.kind == "issue" for item in snapshot.items)
    pull_requests = sum(item.kind == "pull_request" for item in snapshot.items)
    act_now = sum(finding.category == "act_now" for finding in findings)
    ready = sum(finding.category == "ready_to_land" for finding in findings)

    lines = [
        DASHBOARD_MARKER,
        f"# Maintainer Radar: `{_escape(snapshot.repository)}`",
        "",
        f"_Generated {snapshot.generated_at.isoformat()}._",
        "",
        "## Queue health",
        "",
        "| Signal | Count |",
        "| --- | ---: |",
        f"| Open issues | {issues} |",
        f"| Open pull requests | {pull_requests} |",
        f"| Act-now items | {act_now} |",
        f"| Ready-to-land pull requests | {ready} |",
        "",
    ]

    if ai_summary:
        lines.extend(
            [
                "## AI-assisted summary",
                "",
                _escape(ai_summary.strip()),
                "",
                "> This summary is advisory. The deterministic findings below remain the source of truth.",
                "",
            ]
        )

    sections: tuple[tuple[str, Callable[[Finding], bool]], ...] = (
        ("Act now", lambda finding: finding.category == "act_now"),
        ("Review next", lambda finding: finding.category == "review_next"),
        ("Ready to land", lambda finding: finding.category == "ready_to_land"),
        (
            "Stale and unassigned",
            lambda finding: finding.category == "stale" or not finding.item.assignees,
        ),
    )

    for heading, predicate in sections:
        matching = [finding for finding in findings if predicate(finding)][:max_items]
        lines.extend([f"## {heading}", ""])
        if not matching:
            lines.extend(["_No matching items._", ""])
            continue
        for finding in matching:
            lines.extend(_render_finding(finding))

    lines.extend(
        [
            "## How this was scored",
            "",
            (
                f"Configured thresholds: stale after **{config.stale_days} days**; "
                f"review wait after **{config.review_wait_days} days**."
            ),
            "",
            (
                "Scores prioritize human attention. They never authorize merging, closing, "
                "labeling, or assigning an item."
            ),
            "",
            "<sub>Generated by Maintainer Radar.</sub>",
            "",
        ]
    )
    return "\n".join(lines)


def _render_finding(finding: Finding) -> list[str]:
    item = finding.item
    kind = "pull request" if item.kind == "pull_request" else "issue"
    title = _markdown_link_text(item.title)
    lines = [
        f"### [{title} #{item.number}]({item.url})",
        "",
        f"**Score {finding.score}** · {kind} · opened by `@{_escape(item.author)}`",
        "",
    ]
    lines.extend(f"- {_escape(reason)}" for reason in finding.reasons)
    lines.extend(
        [
            f"- **Suggested next step:** {_escape(finding.recommended_action)}",
            "",
        ]
    )
    return lines


def _escape(value: str) -> str:
    return html.escape(value, quote=False)


def _markdown_link_text(value: str) -> str:
    return _escape(value).replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]")
